#pragma once
#include "common.h"
#include "viewer.h"

#include "stringified_shaders.c"


#if DO_DEBUG
#define STRINGIFY_SHADERS
#endif

i32 shader_count = 0;
bool32 are_any_shader_sources_missing;
#define MAX_SHADER_FILENAME 64

void dots_to_underscores(char* s, i32 max) {
	for (char* pos = s; pos < s + max; ++pos) {
		char c = *pos;
		if (c == '\0') break;
		if (c == '.') *pos = '_';
	}
}

const char* one_past_last_slash(const char* s, i32 max) {
	i32 len = strnlen(s, max - 1);
	i32 stripped_len = 0;
	const char* pos = s + len - 1;
	for (; pos >= s; --pos) {
		char c = *pos;
		if (c == '/')  {
			pos += 1; // gone back one too far
			break;
		} else {
			++stripped_len;
		}
	}
	const char* result = pos;
	ASSERT(stripped_len > 0 && stripped_len <= len);
	return result;
}

#ifdef STRINGIFY_SHADERS

// Shader sources can be either loaded from file (preferred, if available), or loaded directly from memory.
// In debug builds, the file stringified_shaders.c is automatically generated, containing the shader sources.
// In this way, the shader sources are embedded in the executable; they do not need to be included in a release package.

#define MAX_SHADERS 32
char shader_filenames[MAX_SHADER_FILENAME][MAX_SHADERS];
char* shader_sources[MAX_SHADERS];

void write_stringified_shaders() {
	if (are_any_shader_sources_missing) {
		return;
	}

	FILE* f_output = fopen("stringified_shaders.c", "w");

	fprintf(f_output, "// This file is automatically generated at runtime.\n\n");

	for (int shader_index = 0; shader_index < shader_count; ++shader_index) {
		char* name = shader_filenames[shader_index];
		dots_to_underscores(name, MAX_SHADER_FILENAME);
		char* source = shader_sources[shader_index];
		i32 source_len = strlen(source);

		// Adapted from bin2c:
		// https://github.com/gwilymk/bin2c

		bool32 need_comma = false;
		fprintf(f_output, "const char stringified_shader_source__%s[%i] = {", name, source_len + 1);
		for (i32 i = 0; i < source_len + 1; ++i) {
			if (need_comma)
				fprintf(f_output, ", ");
			else
				need_comma = 1;
			if ((i % 11) == 0)
				fprintf(f_output, "\n\t");
			if (i == source_len) {
				fprintf(f_output, "0");
			} else {
				fprintf(f_output, "0x%.2x", source[i] & 0xff);
			}
		}
		fprintf(f_output, "\n};\n\n");

	}

	fprintf(f_output, "const char* stringified_shader_sources[%i] = {", shader_count);
	for (int shader_index = 0; shader_index < shader_count; ++shader_index) {
		fprintf(f_output, "\n\tstringified_shader_source__%s,", shader_filenames[shader_index]);
	}
	fprintf(f_output, "\n};\n\n");

	fprintf(f_output, "const char* stringified_shader_source_names[%i] = {", shader_count);
	for (int shader_index = 0; shader_index < shader_count; ++shader_index) {
		fprintf(f_output, "\n\t\"%s\",", shader_filenames[shader_index]);
	}
	fprintf(f_output, "\n};\n\n");

	fclose(f_output);

}



#endif

void load_shader(u32 shader, const char* source_filename) {
	file_mem_t* shader_source_file = platform_read_entire_file(source_filename);
	const char* shader_source = NULL;
	bool32 source_from_file = false;

	if (shader_source_file) {
		source_from_file = true;
		shader_source = (char*) shader_source_file->data;

#ifdef STRINGIFY_SHADERS
		const char* stripped_filename = one_past_last_slash(source_filename, MAX_SHADER_FILENAME);

		ASSERT(shader_count < COUNT(shader_filenames));
		shader_sources[shader_count] = strdup(shader_source);
		strncpy(shader_filenames[shader_count], stripped_filename, MAX_SHADER_FILENAME);
#endif
		++shader_count;
	} else {
		are_any_shader_sources_missing = true;
		const char* stripped_filename = one_past_last_slash(source_filename, MAX_SHADER_FILENAME);
		char source_name_temp[MAX_SHADER_FILENAME] = {};
		strncpy(source_name_temp, stripped_filename, MAX_SHADER_FILENAME);
		dots_to_underscores(source_name_temp, MAX_SHADER_FILENAME);
		for (i32 i = 0; i < COUNT(stringified_shader_source_names); ++i) {
			const char* name = stringified_shader_source_names[i];
			if (strncmp(source_name_temp, name, MAX_SHADER_FILENAME) == 0) {
				shader_source = stringified_shader_sources[i];
			}
		}
	}

	if (!shader_source) {
		printf("Could not locate the shader source for %s.\n", source_filename);
	}

	const char* sources[] = { shader_source, };
	glShaderSource(shader, COUNT(sources), sources, NULL);
	free(shader_source_file);
	glCompileShader(shader);

	i32 success = 0;
	glGetShaderiv(shader, GL_COMPILE_STATUS, &success);
	if (success) {
		/*printf("Shader %s loaded ", source_filename);
		if (source_from_file) {
			printf("(from file).\n");
		} else {
			printf("(from cache).\n");
		}*/
	} else {
		char info_log[2048];
		glGetShaderInfoLog(shader, sizeof(info_log), NULL, info_log);
		printf("Error: compilation of shader '%s' failed:\n%s", source_filename, info_log);
		printf("Shader source: %s\n", shader_source);
	}


}

u32 load_basic_shader_program(const char* vert_filename, const char* frag_filename) {
	u32 vertex_shader = glCreateShader(GL_VERTEX_SHADER);
	u32 fragment_shader = glCreateShader(GL_FRAGMENT_SHADER);

	load_shader(vertex_shader, vert_filename);
	load_shader(fragment_shader, frag_filename);

	u32 shader_program = glCreateProgram();

	glAttachShader(shader_program, vertex_shader);
	glAttachShader(shader_program, fragment_shader);
	glLinkProgram(shader_program);

	{
		i32 success;
		glGetProgramiv(shader_program, GL_LINK_STATUS, &success);
		if (!success) {
			char info_log[2048];
			glGetProgramInfoLog(shader_program, sizeof(info_log), NULL, info_log);
			printf("Error: shader linking failed: %s", info_log);
			panic();
		}
	}

	glDeleteShader(vertex_shader);
	glDeleteShader(fragment_shader);

	return shader_program;
}

static u32 vbo_rect;
static u32 vao_rect;
static bool32 rect_initialized;
static u32 basic_shader;
static bool32 opengl_stuff_initialized;

void init_draw_rect() {
	ASSERT(!rect_initialized);
	rect_initialized = true;

	glGenVertexArrays(1, &vao_rect);
	glBindVertexArray(vao_rect);

	glGenBuffers(1, &vbo_rect);
	glBindBuffer(GL_ARRAY_BUFFER, vbo_rect);

	static float vertices[] = {
			0.0f, 0.0f, 0.0f, 0.0f, 0.0f, // x, y, z,  u, v
			1.0f, 0.0f, 0.0f, 1.0f, 0.0f,
			0.0f, 1.0f, 0.0f, 0.0f, 1.0f,

			0.0f, 1.0f, 0.0f, 0.0f, 1.0f,
			1.0f, 0.0f, 0.0f, 1.0f, 0.0f,
			1.0f, 1.0f, 0.0f, 1.0f, 1.0f,
	};
	glBufferData(GL_ARRAY_BUFFER, sizeof(vertices), vertices, GL_STATIC_DRAW);

	u32 vertex_stride = 5 * sizeof(float);
	glVertexAttribPointer(0, 3, GL_FLOAT, GL_FALSE, vertex_stride, (void*)0); // position coordinates
	glEnableVertexAttribArray(0);
	glVertexAttribPointer(1, 2, GL_FLOAT, GL_FALSE, vertex_stride, (void*)(3*sizeof(float))); // texture coordinates
	glEnableVertexAttribArray(1);


}

void draw_rect(u32 texture) {
	glUseProgram(basic_shader);
	glBindVertexArray(vao_rect);
	glUniform1i(glGetUniformLocation(basic_shader, "the_texture"), 0);
	glBindTexture(GL_TEXTURE_2D, texture);
	gl_diagnostic("glBindTexture");
	glDrawArrays(GL_TRIANGLES, 0, 6);
	gl_diagnostic("glDrawArrays");
}



void init_opengl_stuff() {
	ASSERT(!opengl_stuff_initialized);
	opengl_stuff_initialized = true;

	// TODO: don't depend on seperate shader text files in a release build
	// TODO: look in the executable directory
	basic_shader = load_basic_shader_program("shaders/basic.vert", "shaders/basic.frag");

#ifdef STRINGIFY_SHADERS
	write_stringified_shaders();
#endif
	glEnable(GL_TEXTURE_2D);

	init_draw_rect();
}


typedef struct render_group_t {
	u32 max_pushbuffer_size;
	u32 pushbuffer_size;
	u8* pushbuffer_base;

} render_group_t;

typedef struct render_basis_t {

} render_basis_t;


render_group_t* allocate_render_group(arena_t* arena, u32 max_pushbuffer_size) {
	render_group_t* result = push_struct(arena, render_group_t);
	*result = (render_group_t) {
		.pushbuffer_base = (u8*) push_size(arena, max_pushbuffer_size),
	};
}

void* push_render_entry(render_group_t* group, u32 size) {
	void* result = NULL;
	if (group->pushbuffer_size + size < group->max_pushbuffer_size) {
		result = group->pushbuffer_base + group->pushbuffer_size;
	} else {
		panic();
	}
	return result;
}