#ifndef NDEBUG
#define DO_DEBUG 1
#else
#define DO_DEBUG 0
#endif

#define USE_OPENGL_DEBUG_CONTEXT DO_DEBUG

#define REMOTE_CLIENT_VERBOSE 0
#define TIFF_VERBOSE 0

#define SLIDEVIEWER_VERSION "0.19"

